version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: sunday
      time: '16:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 99
    labels:
      - 'dependencies'
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '> 14.a'
